- CMakeLists.txt
- README.md
merge in release and debug build options
> add release and debug builds

- README.md
- visualize.cu
> cleanup visualize.cu code

- CMakeLists.txt
> pull down april tag library from github

- README.md
- gpu_detector_test.cu
> add a test for cpu/gpu equivalence

- CMakeLists.txt
> add asan and msan options to the build

- install_deps.sh
apt update causes some unwanted behavior.
> add libstdc++-12 as a dependency and remove apt update

- CMakeLists.txt
- app/templates/index.html
- src/json_test.cpp
> Chris.padwick/layout

- app/templates/index.html
The exposure/brightness controls got removed accidentally in a previous commit.  Restore them and also add in proper ranges for the arducam camera.
> restore exposure/brightness controls

- install_deps.sh
implements the changes requested in ticket: https://app.plane.so/team-766/projects/7be56bbc-01ff-4463-9c4d-e29339eea294/issues/e3261675-e01c-4f03-a10b-b480ef27d3ba
PLANE-154
> fix a couple of bugs in install_deps.sh

- README.md
ticket captured here: https://app.plane.so/team-766/projects/7be56bbc-01ff-4463-9c4d-e29339eea294/issues/900f12d7-3fb2-4a45-9f3b-2e866280626a
> update readme file with some fixes

- applycustomargs.sh
see title... I am so tired of my silly code mistakes
> fixed the mv to cp

- .github/workflows/cmake-single-platform.yml
An automated action that will run a build when there are pr's that want to merge to main.
> build action for pull requests

- src/BooleanValueSender.cpp
- src/BooleanValueSender.h
- src/DoubleArraySender.cpp
- src/DoubleArraySender.h
- src/DoubleValueSender.cpp
- src/DoubleValueSender.h
- src/IntegerArraySender.cpp
- src/IntegerArraySender.h
- src/IntegerValueSender.cpp
- src/IntegerValueSender.h
- src/cameraexception.h
- src/ws_server.cu
if the camera is not found, the utility will loop until a camera is found instead of crashing.
> implement retry for missing camera

- app/templates/index.html
- src/ws_server.cu
I added a checkbox to the UI to rotate the image by 180 degrees.  This message gets sent to the web socket server, which then gets sent to the c++ code which rotates the image before sending it through the apriltags pipeline.
> add option to rotate the image by 180 degrees

- app/app.py
- src/ws_server.cu
fix bug where the client keeps disconnecting because of the overwhelming amount of data from the server
> reduce frame rate of imagery sent over web sockets

- app/templates/index.html
Allows for finer adjustment on html side of exposure and brightness. Closes PLANE 225
> Fine adjustment html

- .gitmodules
- Installer/AddAppsToPath.csh
- Installer/AddAppsToPath.sh
- Installer/AprilTags/ApriltagsManager.sh
- Installer/AprilTags/args
- Installer/AprilTagsPipeline.service
- Installer/README.md
- Installer/bin/AprilTags.sh
- Installer/bin/libAprilTags.sh
- Installer/install.sh
- Installer/uninstall.sh
This pr includes two tickets regarding including jetson-clocks to be called when running the Apriltags service on boot and removing the python frontend.
> Updated AprilTags Installer

- Installer/bin/libAprilTags.sh
Short PR, but I fixed some code that I pushed to main.
> Fixed the kill handler

- src/ws_server.cu
changes tag size to correct comp. value.
> fix for tagsize which impacted vision accuracy heavily

- Dockerfile
- install_deps.sh
- ntp.sh
Makes `install_deps.sh` interactive
Adds `ntp` as an installed package
Sets up static IP using netplan
Sets up NTP
> Updating install_deps.sh to include NTP & setup static IPs
